// AUTO-GENERATED from cli/kits/blocks by scripts/sync-kit-to-packages.mjs
// Do not edit this file directly. Edit the kit source instead.

import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
