// AUTO-GENERATED from cli/kits/blocks by scripts/sync-kit-to-packages.mjs
// Do not edit this file directly. Edit the kit source instead.

"use client";

import { Toaster } from "sonner";

export default function AppToaster() {
  return <Toaster position="top-center" richColors closeButton />;
}
