// AUTO-GENERATED from cli/kits/blocks by scripts/sync-kit-to-packages.mjs
// Do not edit this file directly. Edit the kit source instead.

"use client";

import React from "react";
import { EnhancedThemeProvider } from "../components/enhanced-theme-provider";
import type { ThemeVariant } from "../lib/themes";

type BlocksAppProvidersProps = {
  children: React.ReactNode;
  defaultThemeVariant?: ThemeVariant;
};

/**
 * Client-safe provider wrapper for Nextworks blocks (kit-local).
 *
 * This intentionally avoids importing providers/hooks from @nextworks/blocks-core
 * to prevent duplicate React context instances in Turbopack dev.
 */
export function BlocksAppProviders({
  children,
  defaultThemeVariant = "monochrome",
}: BlocksAppProvidersProps) {
  return (
    <EnhancedThemeProvider defaultThemeVariant={defaultThemeVariant}>
      {children}
    </EnhancedThemeProvider>
  );
}
