const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "..", "dist");
const distTypesDir = path.join(__dirname, "..", "dist-types");

if (!fs.existsSync(distDir)) {
  console.error("dist directory not found for @nextworks/blocks-core");
  process.exit(1);
}

if (!fs.existsSync(distTypesDir)) {
  console.error(
    "dist-types directory not found for @nextworks/blocks-core. Did you run build:types?\n",
  );
  process.exit(1);
}

// Copy generated .d.ts files from dist-types into dist so runtime JS and types stay in sync
function copyDtsFiles(srcDir, destDir) {
  const entries = fs.readdirSync(srcDir, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);

    if (entry.isDirectory()) {
      if (!fs.existsSync(destPath)) {
        fs.mkdirSync(destPath, { recursive: true });
      }
      copyDtsFiles(srcPath, destPath);
    } else if (entry.isFile() && entry.name.endsWith(".d.ts")) {
      const contents = fs.readFileSync(srcPath, "utf8");
      fs.writeFileSync(destPath, contents, "utf8");
    }
  }
}

copyDtsFiles(distTypesDir, distDir);

const indexDts = `
// Auto-generated by scripts/postbuild.js
export * from "./lib/themes";
export * from "./lib/utils";
export * from "./components/enhanced-theme-provider";
export * from "./components/theme-provider";
export * from "./providers/BlocksAppProviders";
export * from "./ui/alert-dialog";
export * from "./ui/brand-node";
export * from "./ui/button";
export * from "./ui/card";
export * from "./ui/checkbox";
export * from "./ui/cta-button";
export * from "./ui/dropdown-menu";
export * from "./ui/feature-card";
export * from "./ui/input";
export * from "./ui/label";
export * from "./ui/pricing-card";
export * from "./ui/select";
export * from "./ui/skeleton";
export * from "./ui/switch";
export * from "./ui/table";
export * from "./ui/testimonial-card";
export * from "./ui/textarea";
export * from "./ui/theme-selector";
export * from "./ui/theme-toggle";
export * from "./ui/toaster";
`;

fs.writeFileSync(path.join(distDir, "index.d.ts"), indexDts, "utf8");

const serverDts = `
// Auto-generated by scripts/postbuild.js
// Keep this file in sync with src/server.ts runtime exports.
export { default as AppProviders } from "./components/AppProviders.server";
`;

fs.writeFileSync(path.join(distDir, "server.d.ts"), serverDts, "utf8");
